### PR TITLE
example for kasm config

### PR DESCRIPTION
**Pull request by jakob42**
I created an example of how to use kasm with lldap

### CODE REVIEW

**Review by nitnelave — CHANGES_REQUESTED** [review]
Looks great! Can you add it to the readme?

**Comment by jakob42** [comment]
Sure!

**Review by nitnelave — APPROVED** [review]

**Comment by nitnelave** [comment]
Thanks a lot :)

**Comment by jakob42** [comment]
It's just a drop compared to your work. Thanks!

**Pull request merged**
